# Generated by Django 3.2 on 2021-11-27 06:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionList',
            fields=[
                ('question_id', models.UUIDField(blank=True, default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('question', models.CharField(blank=True, max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='UserInformation',
            fields=[
                ('user_name', models.CharField(max_length=100)),
                ('url_key', models.UUIDField(blank=True, default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('current_three_words', models.CharField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='AnswertoQuestionsPerUser',
            fields=[
                ('ans_que_table_id', models.UUIDField(blank=True, default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('answer_given', models.TextField()),
                ('three_words', models.CharField(blank=True, max_length=1000)),
                ('question_ref_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SnackIdea.questionlist')),
                ('user_ref_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SnackIdea.userinformation')),
            ],
        ),
    ]
